### ISSUE TITLE
Duplicate logs observer in cruise control

### ISSUE THREAD

**Issue by saeedya** [linkedin/cruise-control#2118] opened 2024-02-02 17:46 UTC
On below link
https://github.com/linkedin/cruise-control/blob/137b1fe0552c4aa49ebc900b75786eeee033bbe7/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/async/AbstractAsyncRequest.java
In the method "CruiseControlResponse" , i can see some duplicate logs. This my sample log file:

6231 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:34.908+00:00", "severity": "info", "message": "**### Processing async request CruiseControlStateRequest.**", "metadata":      {"container_name": "cruise-control", "pod_name":  "extra_data": {"file": "**### AbstractAsyncRequest.java", "line": "49"**, }}
6232 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:34.908+00:00", "severity": "info", "message": "**### Processing async request CruiseControlStateRequest.**", "metadata":      {"container_name": "cruise-control", "pod_name":  "extra_data": {"file": "**### AbstractAsyncRequest.java", "line": "49"**, }}
6299 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:35.066+00:00", "severity": "info", "message": "**### Computation is completed for async request: /state.", "metadata":**      {"container_name": "cruise-control", "pod_name": "extra_data": {"file": "**### AbstractAsyncRequest.java", "line": "57"**, }}
6300 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:35.066+00:00", "severity": "info", "message": **### "Computation is completed for async request: /state.", "metadata":**      {"container_name": "cruise-control", "pod_name": "extra_data": {"file": **### "AbstractAsyncRequest.java", "line": "57"**, }}
6301 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:35.094+00:00", "severity": "info", **### "message": "127.0.0.1 - user [02/Feb/2024:14:49:34 +0000] \"GET /kafkacruiseco     ntrol/state HTTP/1.1\"** 200 1095", "metadata": {"container_name": "cruise-control", "pod_name":  "extra_data": **### {"file": "Slf4jRequestLogWriter.java     ", "line": "62"**, }}
6302 {"version": "1.2.0", "timestamp": "2024-02-02T14:49:35.094+00:00", "severity": "info", ### "message": "127.0.0.1 - user [02/Feb/2024:14:49:34 +0000] \"GET /kafkacruiseco     ntrol/state HTTP/1.1\" 200 1095", "metadata": {"container_name": "cruise-control", "pod_name":  "extra_data": **### {"file": "Slf4jRequestLogWriter.java     ", "line": "62"**, }}

Regards,
Saeed

**Comment by saeedya** [comment] 2024-02-08 13:25
Hi @scholzj
Can you please help me with this?
Kind Regards,
Saeed

**Comment by scholzj** [comment] 2024-02-08 13:46
I have no idea I'm afraid - I do not know much about Cruise Control.

**Comment by marcelloromani** [comment] 2024-03-07 22:10
Why do you think there's duplication? What would you change in the log message?

**Comment by vasilisa-za** [comment] 2024-03-24 22:22
Root cause of the issue seems to be log4j configuration [here](https://github.com/linkedin/cruise-control/blob/2.5.137/config/log4j.properties). `kafkaCruiseControlFile` appender added for both `root` and  `com.linkedin.kafka.cruisecontrol` loggers, resulting in messaged being appended twice.

Verified by running by simple test locally:
1. Same appender added for two intersected loggers results in duplicated message:
![image](https://github.com/linkedin/cruise-control/assets/66975631/d2b9f8bd-66df-496c-8d00-24f2e3a7dda8)

2. Commenting out appender for one of the loggers removes message duplication:
![image](https://github.com/linkedin/cruise-control/assets/66975631/00955faf-513b-41d1-8f1b-2dfb230ef77f)

**Comment by vasilisa-za** [comment] 2024-03-24 22:49
Looks like original intent of logging everything into console and additionally `com.linkedin.kafka.cruisecontrol` into dedicated file appender was broken in [this PR](https://github.com/linkedin/cruise-control/commit/2d0d371274fc4e990811ed4d418562e5fcccc964#diff-01c754c790ab1133cbd4936bf58ee367ed76839996d9c2d77892801f24eee4b7).

Could you please assign this issue to me, so I could raise a PR to fix it?

**Comment by agriffaut** [comment] 2024-06-27 12:22
Hello,

I have the same issue, but your PR do not looks good to me.
By removing `kafkaCruiseControlAppender` from the rootLogger we loose all logs not catched by other loggers :/

The issue is in fact on the `appenderRef.kafkaCruiseControlAppender.ref` which forward events catched by the attached logger, which are also forwarded by the rootLogger !
Removing those two `appenderRef` will do the job.

Also setting `additivity=false` to `logger.operationLogger` and `logger.CruiseControlPublicAccessLogger` will prevent the `rootLogger` to catch them too.

Regards

**Comment by mhratson** [comment] 2024-08-28 03:11
closing as per [comment](https://github.com/linkedin/cruise-control/issues/2118#issuecomment-2194542735)

**Closed by mhratson** 2024-08-28 03:11 UTC
Labels: good first issue, productivity
