### ISSUE TITLE
processAlterPartitionReassignmentsResult and TimeoutException

### ISSUE THREAD

**Issue by psycotica0-shopify** [linkedin/cruise-control#1331] opened 2020-09-23 20:33 UTC
We started having an issue in one of our clusters this week, and I think I've narrowed it down, but I'm not sure what the expected behaviour is. We're running Cruise Control 2.4.20.

We were seeing the cluster start to self-heal, but then it would get an exception and stop. The executor would be in "No Task In Progress", and it would complain about Rack Awareness until the moves it itself had created were finished. Then it would do it all over again.

The issue seems to be that the admin API request has a timeout (hard-coded) of 120 seconds, and the future has a hard-coded timeout of 10 seconds.

But that's ok!
The smaller timeout isn't the problem. The problem is that when there are a lot of partitions moving, all of the admin API calls are started together, which starts the clocks for those timeouts, but the futures appear to be read serially.

So the first 11 get the first timeout (the one on the Future) after 10 seconds of waiting, which logs a warning and moves on, but the 12th one has a timeout waiting for it when it gets there, leading to a timeout wrapped in an exception.

The first one (not disruptive):
```
Failed to process AlterPartitionReassignmentsResult of _core-sieve-_core-shard56-data-dedup-changelog-25. java.util.concurrent.TimeoutException
  at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
  at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
  at com.linkedin.kafka.cruisecontrol.executor.ExecutionUtils.processAlterPartitionReassignmentsResult(ExecutionUtils.java:340)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.waitForInterBrokerReplicaTasksToFinish(Executor.java:1359)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.interBrokerMoveReplicas(Executor.java:1173)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.execute(Executor.java:994)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.run(Executor.java:920)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

The second one (breaks everything):
```
Executor got exception during execution java.lang.IllegalStateException: core-sale_unit_costs-0 encountered an unknown execution exception.
  at com.linkedin.kafka.cruisecontrol.executor.ExecutionUtils.processAlterPartitionReassignmentsResult(ExecutionUtils.java:355)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.waitForInterBrokerReplicaTasksToFinish(Executor.java:1359)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.interBrokerMoveReplicas(Executor.java:1173)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.execute(Executor.java:994)
  at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.run(Executor.java:920)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException:
Aborted due to timeout.
  at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
  at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
  at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:104)
  at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
  at com.linkedin.kafka.cruisecontrol.executor.ExecutionUtils.processAlterPartitionReassignmentsResult(ExecutionUtils.java:340)
  ... 9 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Aborted due to timeout.
```

So I have a few questions. Should we even be expecting so many admin API timeouts? Is this the expected source of back-pressure, or is something else breaking to even have this many timeouts in the first place? I've done some hacking to get things to run. We have a 78 node cluster, so if we turn the number of concurrent moves to 1, and hack the admin API timeout to be 900 seconds (15 minutes!) then it will work, because it only needs 780 seconds to read all the futures and timeout there. That obviously doesn't scale, though, right? If that _is_ the plan, then we should make that admin API client timeout configurable.

I feel like the real fix, assuming the answer to question 1 is "yes, we expect there to be many admin API timeouts", is to have the _inner_ (API) timeout be thrown to the outer (future) context _as_ a Timeout, rather than wrapped, so the two are now the same case. They get logged as a warning and we move on. Does that seem like the right solution? Is it troublesome to have all these futures hanging around with already thrown timeout exceptions waiting in them?

I don't know enough about how this system is expected to function to know how it's supposed to look.

**Comment by efeg** [comment] 2020-09-24 19:35
@psycotica0-shopify  Thanks for reporting this issue!
1. This many timeouts in a cluster of ~80 brokers is not expected. I am curious to see what was keeping the controller busy. Does CC ever respond to CC requests or does it keep timing out? Increasing the `execution.progress.check.interval.ms` config can also help -- CC will send fewer admin client requests to controller.
2. We should add some parallelization to the serial check over the values of `AlterPartitionReassignmentsResult` -- this is a good point.
3. Regardless of whether these timeouts are expected, we should make these hardcoded timeouts configurable,
4. We should handle the inner timeout gracefully -- i.e. it should not terminate the execution. I suspect that a separate inner catch block for it would be useful for logging purposes (rather than throwing it to the outer context).

Would you be interested in submitting a PR for this?

**Comment by psycotica0-shopify** [comment] 2020-09-29 15:17
> Does Kafka ever successfully respond to CC's AdminClient requests or does it keep timing out? 

I'm not sure. I assume it responds successfully at some point to some of the requests, since partitions do move. In order to tell more I'd have to run a debug build against production. But some partitions did move. I tried to do a bit of digging into the broker code to figure out what steps it takes before returning success to this call, but didn't make it too far before I ended up in queues of queues. It does go through a throttle at some point, though. Maybe our throttles were triggering and slowing down requests? Either way, when I hard-coded a 10 minute timeout I was still seeing timeouts, which felt long to me...

> Would you be interested in submitting a PR for this?

I'm interested in at point 4, but I can't guarantee I'll make something in any kind of timeframe, given other things I have going on.

**Comment by psycotica0-shopify** [comment] 2020-10-26 19:06
I did point 4 in https://github.com/linkedin/cruise-control/pull/1360

Running it in production over the weekend allowed the entire operation to run for days and days without interruption and complete successfully.
This is great!

But you're also right, it wasn't all good. This allowed the errors to not abort the code, but it didn't stop them from happening. And this DoS on the admin api started affecting other systems as well, such as our topic-management workflow, which goes through that same API.

I tried changing `execution.progress.check.interval.ms` from 10s to 60s, expecting fewer to even 0 timeouts, but it doesn't appear to have had any effect.
The number of timeout error logs I saw was the same before and after I changed it.

So either I need to pick an even higher number, or something else in here is clogging up the admin API.
I'll see if I can figure out what the controller is actually doing, and get back to you.

**Comment by efeg** [comment] 2021-07-01 20:50
Closing the issue as I believe the latest version of the code (see https://github.com/linkedin/cruise-control/pull/1360 and https://github.com/Lincong/cruise-control/pull/4) has introduced the necessary knobs and exception handling. Please reopen if you feel if the issue is ongoing.

**Closed by efeg** 2021-07-01 20:50 UTC
Labels: robustness
