### ISSUE TITLE
Are user-provided goals in kafkarebalance spec treated as hard goals?

### ISSUE THREAD

**Issue by sreelu27** [linkedin/cruise-control#2117] opened 2024-01-31 10:03 UTC
Scenario: is below goals treated as hard goals

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaRebalance
metadata:
  name: my-rebalance
  labels:
    strimzi.io/cluster: my-cluster
spec:
  goals:
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal 
```

**Comment by kyguy** [comment] 2024-02-21 18:05
This is a duplicate of https://github.com/linkedin/cruise-control/issues/2111 and can be closed

**Comment by CCisGG** [comment] 2024-02-21 18:50
Thanks @kyguy for the answer!

**Closed by CCisGG** 2024-02-21 18:50 UTC
Labels: question
