### ISSUE TITLE
kafka automate

### ISSUE THREAD

**Issue by ThreeEarthGod** [linkedin/cruise-control#343] opened 2018-09-29 08:03 UTC
Hi,Friend, I want to ask if Cruise Control can automate the expansion of kafka clusters, how to expand, and when to provide management interfaces.thanks.

**Comment by efeg** [comment] 2018-10-01 23:37
Duplicate of https://github.com/linkedin/cruise-control/issues/344.

**Closed by efeg** 2018-10-01 23:37 UTC
