### ISSUE TITLE
Skipped broker failure fix is not applied later

### ISSUE THREAD

**Issue by functicons** [linkedin/cruise-control#653] opened 2019-04-11 00:06 UTC
I created a 5-node test cluster with 3 topics, each with 3 partitions and replication_factor=3. I enabled broker failure self healing and changed alert threshold to 2 min and healing threshold to 5 min. Then I deliberately shutdown one node, and verified CC detected it as expected, but the fix was skipped, because there is no traffic in the cluster, CC couldn't collect enough info. This is expected. But the problem is that, then I started to continuously generate some traffic with:

```
 bin/kafka-producer-perf-test.sh --topic topic-1 --num-records 100000000 --record-size 100 --throughput 1000 --producer-props  bootstrap.servers=localhost:9092
```

After >1 hour, the AnomalyDetectorState is still COMPLETENESS_NOT_READY, the skipped fix is still not applied, and the under-replicated partitions are still there.

The problem doesn't exist, if I first generate traffic for a few minutes, then shutdown a broker. In this case, the fix is applied timely.

**Comment by efeg** [comment] 2019-04-30 01:37
@functicons I was unable to reproduce this scenario -- did you observe any `WARN`-level logs from `CruiseControlMetricsProcessor` such as `Skip generating metric samples for partition XXX`? -- The relevant code path in broker failure detection seems to apply the skipped broker failures when completeness is ready. I suspect that generating traffic to only `topic-1`, might potentially be insufficient to satisfy overall completeness requirements.

-- That being said, checking this issue also helped improving performance and accuracy of anomaly detector (i.e. https://github.com/linkedin/cruise-control/pull/682).

**Comment by efeg** [comment] 2019-05-21 05:35
Closing the issue as it was not reproducable.
@functicons Please feel free to reopen if you encounter this again -- more logs and the response of the state endpoint would be useful. I suspect that some error in sample collection would have caused continuous `COMPLETENESS_NOT_READY` issue.

**Closed by efeg** 2019-05-21 05:35 UTC
