### ISSUE TITLE
Not able to add_broker a new kafka broker

### ISSUE THREAD

**Issue by jmarkan** [linkedin/cruise-control#214] opened 2018-04-30 14:35 UTC
Hello @efeg @becketqin 
Here is my use case: I have a 6-broker cluster and 1 of the broker got terminated. Cruise Control did see that and was able to automatically re-balance the data on remaining 5 brokers in no time. However, when I'm trying to do a POST query to add_broker for adding the new Kafka broker to the cluster, it is failing with the following error:

`"stackTrace": "java.util.concurrent.ExecutionException: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException\n\tat java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)\n\tat com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getAndMaybeReturnProgress(KafkaCruiseControlServlet.java:1269)\n\tat com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.addOrRemoveBroker(KafkaCruiseControlServlet.java:1091)\n\tat com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doPost(KafkaCruiseControlServlet.java:443)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:564)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)\n\tat org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)\n\tat org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException\n\tat com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.addBrokers(KafkaCruiseControl.java:177)\n\tat com.linkedin.kafka.cruisecontrol.async.AddBrokerRunnable.getResult(AddBrokerRunnable.java:41)\n\tat com.linkedin.kafka.cruisecontrol.async.AddBrokerRunnable.getResult(AddBrokerRunnable.java:17)\n\tat com.linkedin.kafka.cruisecontrol.async.OperationRunnable.run(OperationRunnable.java:45)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\nCaused by: java.lang.NullPointerException\n\tat com.linkedin.kafka.cruisecontrol.model.Broker.<init>(Broker.java:61)\n\tat com.linkedin.kafka.cruisecontrol.model.Host.createBroker(Host.java:122)\n\tat com.linkedin.kafka.cruisecontrol.model.Rack.createBroker(Rack.java:254)\n\tat com.linkedin.kafka.cruisecontrol.model.ClusterModel.createBroker(ClusterModel.java:605)\n\tat com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:452)\n\tat com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:388)\n\tat com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.addBrokers(KafkaCruiseControl.java:167)\n\t... 8 more\n",
    "error": "Error processing POST request '/add_broker' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException'."`

kafkacruisecontrol/state looks to be okay with no issues. I'm wondering if this issue is related to: #https://github.com/linkedin/cruise-control/issues/183. Maybe a proposal was getting precomputed at the time I tried to do a   ##add_broker? 

Additionally, I'm also getting an error on /load:
Error processing GET request '/load' due to 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException'.

/proposals gives the following output:
![image](https://user-images.githubusercontent.com/14930180/39433095-0bd123e8-4c63-11e8-9040-910edf369034.png)

**Comment by efeg** [comment] 2018-05-01 00:56
Hi @jmarkan 
Can you share the `git hash` of your current `HEAD`? There was a known issue fixed in `PR-198` -- i.e. `a484de7aed79d3e55d7a96dcee76162a32ef12aa`. Could you confirm that you have this fix in your local copy?

**Comment by jmarkan** [comment] 2018-05-01 10:33
Hi @efeg 
1. Here is the hash of the Head:
`cat .git/refs/heads/master
54c6eaaccd197d926f810478c558057596107397`

2. The user-provided `brokercapacity` doesn't look like `null` in file: `cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java#L450`
`Map<Resource, Double> brokerCapacity =
            _brokerCapacityConfigResolver.capacityForBroker(rack, node.host(), node.id());`

**Comment by efeg** [comment] 2018-05-01 16:17
Hi @jmarkan ,
Based on the given stack trace and the git hash, I still suspect that the exception might be due to a `null` value of `brokercapacity` passed to the broker constructor -- i.e. see the following part of the stack trace:
```
Caused by: java.lang.NullPointerException
at com.linkedin.kafka.cruisecontrol.model.Broker.<init>(Broker.java:61)
at com.linkedin.kafka.cruisecontrol.model.Host.createBroker(Host.java:122)
at com.linkedin.kafka.cruisecontrol.model.Rack.createBroker(Rack.java:254)
at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createBroker(ClusterModel.java:605)
at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:452)
at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:388)
at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.addBrokers(KafkaCruiseControl.java:167)
```
Note that this value is received from the pluggable `broker.capacity.config.resolver.class`. Unless you explicitly provide a broker capacity config resolver, the default one is going to be used --
 i.e. `BrokerCapacityConfigFileResolver`.

Did you by any chance modify the 1) `capacity.config.file` config to point to some other file, or 2) remove `"brokerId": "-1",` from `config/capacity.json`?

**Comment by jmarkan** [comment] 2018-05-02 12:04
Hi @efeg 
Yes, I did modify `config/capacity.json` file and replaced the referenced brokers in there with the ones I have. Maybe I didn't understand properly the role of this config and hence ended up modifying it. Looks like its the cause of the problem I'm facing. Should I roll back the original `capacity.json`file and bounce Cruise Control?

**Comment by efeg** [comment] 2018-05-02 16:14
Hi @jmarkan 
You should indeed modify this file to create a map of the `brokerId -> capacity` for the brokers in your cluster.
I believe the issue is for some broker, the actual id of the broker is not the same as what you expect to see -- i.e. you have a mapping in the `capacity.json` for a broker with the expected broker id, but the actual broker id of that broker is different from what you expect.
In case a particular broker id is missing from the `capacity.json` file, `BrokerCapacityConfigFileResolver` is configured to use the default broker id capacity, which is identified with id `-1`. Is it possible that the mapping of `"brokerId": "-1"` (the default capacity for brokers with missing id) is also removed from this file?
I believe if you would identify the broker for which this exception is thrown, and add the relevant capacity to the `capacity.json`, that would resolve the issue.

**Comment by jmarkan** [comment] 2018-05-02 16:31
Hey @efeg 
I see. Yes, I removed broker id: -1 and broker id:0  mappings from capacity.json and replaced them with the broker IDs of the actually monitored kafka cluster. So the situation that was there was that there were 6 brokers configured in capacity.json and one of the brokers got terminated and a new one was autoscaled with obviously new broker id. And that new broker id was not there in capacity.json (I missed to add it).

So I guess I need to do a couple of things to resolve this issue:

1. Bring back broker id:0 and -1 mapping in capacity.json.
2. Replace the old/terminated broker id mapping with the new one in capacity.json
3. Restart Cruise Control so it ingests the updated capacity.json (BTW it'll be good to have cruise control restart/start script part of the package).

Sounds good?

**Comment by efeg** [comment] 2018-05-02 16:47
1. If broker id 0 does not exist in your cluster, there is no need to add it back (it has no harm though). Adding `-1` ensures that if you forget to add the capacity of a new broker, the new broker will use the capacity defined by the default broker.
2. No need to remove the old broker id, but you can.
3. Sounds good.

**Closed** 2018-05-08 00:44 UTC
