### ISSUE TITLE
Peak in metrics

### ISSUE THREAD

**Issue by KSI47** [linkedin/cruise-control#1325] opened 2020-09-10 13:29 UTC
I'm using self-healing feature in cc, i wanted to know if cc detects a goal violation if there was a quick peak in metrics (in a whole snapshot of 5 mins) that violated a goal (eg resources usage) and went away quickly ? if no how to consider over-passing a certain threshold for a small amount of time as an actual violation?

**Comment by efeg** [comment] 2020-09-11 17:50
Hi @KSI47 
Detecting such transient bursts in metrics (e.g. CPU utilization) can be achieved by keeping a short load history and running frequent goal violation checks -- e.g. `num.partition.metrics.windows` of 1, a small `partition.metrics.window.ms`, and a small `goal.violation.detection.interval.ms`.

**Comment by KSI47** [comment] 2020-09-15 21:12
My comment wasn't enough clear, what i meant is that we don't want for our anomaly detecor to raise up a goal violation flag only because of some peak in consumption in a short time, can you explain more about that please ? and also why do we keep partition windows (i mean in one single snapshot, we need to aggregate partition metrics in only one window num.partition.metrics.windows=1), i didn't get why do we need more than 1 partition window to get a proposal ?

**Comment by efeg** [comment] 2020-10-14 21:09
Closing this issue as the latest comment is a duplicate of https://github.com/linkedin/cruise-control/issues/1344.

**Closed by efeg** 2020-10-14 21:09 UTC
Labels: duplicate, question
